rules:
  - id: commit-traceability
    description: "Do not require issue references in individual commits"
    applies_to: commit_messages
    condition: "must_not contain '#[0-9]+'"
    severity: warning
